<?php
vc_map(array(
	"name" => esc_html__("Social Accounts", 'pixi'),
	"base" => "social_accounts",
	"category" => esc_html__('Extra Elements', 'pixi'),
	"icon" => "tb-icon-for-vc fa fa-share-alt",
	"params" => array(
			array(
				'type'				=> 'param_group',
				'heading'			=> esc_html__('Social networks', 'pixi'),
				'param_name'		=> 'social_networks',
				'params'			=> array(
					array(
						'type'			=> 'dropdown',
						'heading'		=> esc_html__('Social network', 'pixi'),
						'param_name'	=> 'social_icons',
						'value'			=> array(
							esc_html__('Twitter', 'pixi')			=> 'twitter',
							esc_html__('Facebook', 'pixi')			=> 'facebook',
							esc_html__('Dribbble', 'pixi')			=> 'dribbble',
							esc_html__('Deviantart', 'pixi')		=> 'deviantart',
							esc_html__('Flickr', 'pixi')			=> 'flickr',
							esc_html__('Instagram', 'pixi')			=> 'instagram',
							esc_html__('LinkedIN', 'pixi')			=> 'linkedin',
							esc_html__('Pinterest', 'pixi')			=> 'pinterest',
							esc_html__('RSS', 'pixi')				=> 'rss',
							esc_html__('Tumblr', 'pixi')			=> 'tumblr',
							esc_html__('Vimeo', 'pixi')				=> 'vimeo',
							esc_html__('YouTube', 'pixi')			=> 'youtube',
							esc_html__('Skype', 'pixi')				=> 'skype',
							esc_html__('Soundcloud', 'pixi')		=> 'soundcloud',
							esc_html__('Behance', 'pixi')			=> 'behance',
						),
					),
					array(
						'type'				=> 'vc_link',
					    'heading'           => esc_html__("URL", 'pixi'),
						'param_name'		=> 'soc_url',
						'value'				=> 'url:%23|||',
						'edit_field_class'	=> 'vc_column vc_col-sm-6 no-top-padding crum_vc',
					),
				),
			 ),
	    array(
		    "type" => "dropdown",
			"class" => "",
			"heading" => esc_html__("color", 'pixi'),
			"param_name" => "color",
			"value" => array(
				esc_html__('colors', 'pixi') => 'colors',
	            esc_html__('gradient', 'pixi') => 'gradient',
				esc_html__('primary', 'pixi') => 'primary',
				esc_html__('secondary', 'pixi') => 'secondary',
				esc_html__('white', 'pixi') => 'white',
				esc_html__('grey', 'pixi') => 'grey',
				esc_html__('dark', 'pixi') => 'dark',
			),
		),
	       array(
				"type" => "dropdown",
				"class" => "",
				"heading" => esc_html__("Style", 'pixi'),
				"param_name" => "style",
				"value" => array(
					esc_html__('Style 1', 'pixi') => 'style1',
					esc_html__('Style 2', 'pixi') => 'style2',
					esc_html__('Style 3', 'pixi') => 'style3',
				),
				"description" => esc_html__('Select style in this elment.', 'pixi')
	    	),
	       array(
				'type'				=> 'dropdown',
				'param_name'		=> 'alignment',
				'heading'           => esc_html__("horizontal alignment", 'pixi'),
				'value'			    => array(
					esc_html__('Center', 'pixi') => 'center',
					esc_html__('Left', 'pixi')	=> 'left',
					esc_html__('Right', 'pixi')	=> 'right'
				),
			),
	        array(
            'type' => 'dropdown',
            'heading' => esc_html__( 'Animation CSS', 'pixi' ),
            'value' => array(
	            esc_html__( 'none', 'pixi' )          => 'none',
                esc_html__( 'bounceIn', 'pixi' )      => 'wow bounceIn',
                esc_html__( 'bounceInDown', 'pixi' )  => 'wow bounceInDown',
                esc_html__( 'bounceInLeft', 'pixi' )  => 'wow bounceInLeft',
			    esc_html__( 'bounceInRight', 'pixi' ) => 'wow bounceInRight',
			    esc_html__( 'bounceInUp', 'pixi' )    => 'wow bounceInUp',
			    esc_html__( 'fadeIn', 'pixi' )        => 'wow fadeIn',
			    esc_html__( 'fadeInDown', 'pixi' )    => 'wow fadeInDown',
			    esc_html__( 'fadeInDownBig', 'pixi' ) => 'wow fadeInDownBig',
			    esc_html__( 'fadeInLeft', 'pixi' )    => 'wow fadeInLeft',
			    esc_html__( 'fadeInLeftBig', 'pixi' ) => 'wow fadeInLeftBig',
			    esc_html__( 'fadeInRight', 'pixi' )   => 'wow fadeInRight',
			    esc_html__( 'fadeInRightBig', 'pixi' )=> 'wow fadeInRightBig',
			    esc_html__( 'fadeInUp', 'pixi' )      => 'wow fadeInUp',
			    esc_html__( 'fadeInUpBig', 'pixi' )   => 'wow fadeInUpBig',
			    esc_html__( 'flipInX', 'pixi' )       => 'wow flipInX',
			    esc_html__( 'flipInY', 'pixi' )       => 'wow flipInY',
                esc_html__( 'slideInUp', 'pixi' )     => 'wow slideInUp',
                esc_html__( 'slideInDown', 'pixi' )   => 'wow slideInDown',
			    esc_html__( 'slideInLeft', 'pixi' )   => 'wow slideInLeft',
			    esc_html__( 'slideInRight', 'pixi' )  => 'wow slideInRight',
			    esc_html__( 'zoomIn', 'pixi' )        => 'wow zoomIn',
			    esc_html__( 'zoomInDown', 'pixi' )    => 'wow zoomInDown',
			    esc_html__( 'zoomInLeft', 'pixi' )    => 'wow zoomInLeft',
			    esc_html__( 'zoomInRight', 'pixi' )   => 'wow zoomInRight',
			    esc_html__( 'zoomInUp', 'pixi' )      => 'wow zoomInUp',
				),
				'param_name' => 'animation_css',
				'description' => esc_html__( 'Select animation type.', 'pixi' ),
			),
			array(
				'type' => 'dropdown',
				'heading' => esc_html__( 'Animation Delay', 'pixi' ),
				'value' => array(
					esc_html__( '0.1s', 'pixi' ) => '0.1s',
					esc_html__( '0.2s', 'pixi' ) => '0.2s',
					esc_html__( '0.3s', 'pixi' ) => '0.3s',
					esc_html__( '0.4s', 'pixi' ) => '0.4s',
					esc_html__( '0.5s', 'pixi' ) => '0.5s',
					esc_html__( '0.6s', 'pixi' ) => '0.6s',
					esc_html__( '0.7s', 'pixi' ) => '0.7s',
					esc_html__( '0.8s', 'pixi' ) => '0.8s',
					esc_html__( '0.9s', 'pixi' ) => '0.9s',
				),
				'param_name' => 'animation_delay',
				'description' => esc_html__( 'Select animation delay.', 'pixi' ),
			),
			array(
				'type'				=> 'textfield',
				'param_name'		=> 'el_class',
	            'heading'           => esc_html__("Extra Class", 'pixi'),
			    'description'       => esc_html__( "If you wish to style particular content element differently, then use this field to add a class name and then refer to it in your css file.", 'pixi' ) 
			),
	)
));